export const API_BASE_URL = process.env.REACT_APP_TEST_API_BASE_URL;

export const FETCH_PAYMENTS = 'FETCH_PAYMENTS';
export const FETCH_BALANCES = 'FETCH_BALANCES';
export const FETCH_ACCOUNT_INFO = 'FETCH_ACCOUNT_INFO';

export const CLIENT_LOGIN = "CLIENT_LOGIN";
export const CLIENT_LOGOUT = "CLIENT_LOGOUT";
export const CLIENT_ERROR = "CLIENT_ERROR";

export const CREATE_FLASH_MESSAGE = 'CREATE_FLASH_MESSAGE';
export const FETCH_ALL_FLASH_MESSAGES = 'FETCH_ALL_FLASH_MESSAGES';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';